-- Q1 --
-- SELECT DEPARTMENT_ID, JOB_ID   
-- FROM HR.EMPLOYEES
-- MINUS
-- SELECT DEPARTMENT_ID, JOB_ID
-- FROM HR.EMPLOYEES
-- WHERE JOB_ID = 'ST_CLERK';



-- SELECT *
-- FROM HR.DEPARTMENTS;

-- SELECT *
-- FROM HR.LOCATIONS;

-- SELECT *
-- FROM HR.COUNTRIES;



-- SELECT *
-- FROM HR.DEPARTMENTS D
-- JOIN HR.LOCATIONS L
-- ON D.LOCATION_ID = L.LOCATION_ID
-- JOIN HR.COUNTRIES C
-- ON L.COUNTRY_ID = C.COUNTRY_ID;


-- GET ALL COUNTRIES
-- THEN EXCLUDE COUNTRIES WITH NO DEPARTMENTS
-- Q2 --
-- SELECT COUNTRY_ID, COUNTRY_NAME
-- FROM HR.COUNTRIES
-- MINUS
-- SELECT L.COUNTRY_ID, C.COUNTRY_NAME
-- FROM HR.DEPARTMENTS D
-- JOIN HR.LOCATIONS L
-- ON D.LOCATION_ID = L.LOCATION_ID
-- JOIN HR.COUNTRIES C
-- ON (L.COUNTRY_ID = C.COUNTRY_ID);




-- Q3 --
-- SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID
-- FROM HR.EMPLOYEES
-- WHERE DEPARTMENT_ID = 50
-- UNION
-- SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID
-- FROM HR.EMPLOYEES
-- WHERE DEPARTMENT_ID = 80;

-- SELECT *
-- FROM HR.EMPLOYEES E
-- JOIN HR.DEPARTMENTS D
-- ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID);

-- SELECT * FROM HR.JOBS;



-- SALES REP AND WORK IN SALES DEP
-- Q4 --
-- SELECT EMPLOYEE_ID
-- FROM HR.EMPLOYEES
-- INTERSECT 
-- SELECT E.EMPLOYEE_ID
-- FROM HR.EMPLOYEES E
-- JOIN HR.JOBS J
-- ON (E.JOB_ID = J.JOB_ID)
-- WHERE J.JOB_TITLE = 'Sales Representative';
-- INTERSECT
-- SELECT E.EMPLOYEE_ID
-- FROM HR.EMPLOYEES E
-- JOIN HR.DEPARTMENTS D
-- ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
-- WHERE D.DEPARTMENT_NAME = 'Sales'
--     );







-- REGARDLESS MEANS UNION and adding the default null column
-- Q5 --
SELECT LAST_NAME, DEPARTMENT_ID, TO_CHAR(NULL) DEPARTMENT_NAME
FROM HR.EMPLOYEES
UNION
SELECT TO_CHAR(NULL) LAST_NAME, DEPARTMENT_ID, DEPARTMENT_NAME
FROM HR.DEPARTMENTS;



